### PR TITLE
fix non-matching object selector

### PR DESCRIPTION
**Pull request by illes**
Fix for `select json_get_object('{"name":"steven"}', '$.name');` not returning `steven` but `NULL`.

### CODE REVIEW

**Comment by nazgul33** [comment]
hi illes, can you share your build/testing environment?
I'm testing on impala 2.2.0-cdh5.4.8 release build, centos 6.4 x64.
here's my test on the system described above (your patch not applied)

[XXXXXXXXXXX:21000] > select gshare.get_json_object('{"name":"steven"}', '$.name');
Query: select gshare.get_json_object('{"name":"steven"}', '$.name')
+-------------------------------------------------------+
| gshare.get_json_object('{"name":"steven"}', '$.name') |
+-------------------------------------------------------+
| steven                                                |
+-------------------------------------------------------+

**Comment by illes** [comment]
almost identical:
- fully patched debian 7 (wheezy) x64
- gcc 4.7.2
- impala 2.2.0-cdh5.4.8

**Comment by nazgul33** [comment]
I believe this bug might be fixed by changing rapidjson name space
as in 
https://github.com/nazgul33/impala-get-json-object-udf/pull/4
can you confirm?

**Comment by illes** [comment]
I confirm, that the merged #4 fixes the issue

**Pull request closed without merging**
